apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-logistics-pipeline
  labels:
    app: smart-logistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-logistics
  template:
    metadata:
      labels:
        app: smart-logistics
    spec:
      containers:
      - name: smart-logistics
        image: smart-logistics-supply-chain-ml:latest
        ports:
        - containerPort: 8080
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-service:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: smart-logistics-service
spec:
  selector:
    app: smart-logistics
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
