apiVersion: 1

datasources:
  - name: Evidently_Monitoring
    type: postgres
    access: proxy
    url: mlflow-postgres:5432
    database: monitoring
    user: mlflow
    secureJsonData:
      password: mlflow
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    isDefault: false
    editable: true
    version: 1
    orgId: 1
